apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: papers
spec:
  replicas: 2
  template:
    metadata:
      labels:
         app: papers
    spec:
      containers:
        - image: gcr.io/larson-deployment/papers:73c809c037065480c2546681f0841a57b7600464
          ports:          
            - containerPort: 9292
          readinessProbe:
            httpGet:
              path: /health
              port: 9292
            initialDelaySeconds: 5
            timeoutSeconds: 1	
          env:
            - name: "MEMCACHE_HOSTS"
              value: "10.71.246.192:11211"
            - name: "GH_BASIC_CLIENT_ID"
              value: "<>"
            - name: "GH_BASIC_SECRET_ID"
              value: "<>"
            - name: "MYSQL_HOST"
              value: "127.0.0.1"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: "MYSQL_DB"
              value: "papers"
            - name: "DOMAIN"
              value: "https://systemsandpapers.com"
            - name: "GOOGLE_ANALYTICS_ID"
              value: "<>"
            - name: "RACK_ENV"
              value: "production"
          imagePullPolicy: Always
          name: papers
        - image: gcr.io/cloudsql-docker/gce-proxy:1.09
          name: cloudsql-proxy
          command: ["/cloud_sql_proxy", "--dir=/cloudsql", "-instances=larson-deployment:us-central1:papers=tcp:3306", "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
            
