apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cert-refresh
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cert-refresh
    spec:
      containers:
      - image: gcr.io/larson-deployment/cert-refresh:b8ccb3e9d464d0ab1db59b5576efb94ce6b87767
        imagePullPolicy: Always
        name: cert-refresh
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1	
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1	
